# Generated by Django 3.1.5 on 2021-02-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='product_price',
            field=models.FloatField(default=0),
        ),
    ]
