# Generated by Django 3.1.5 on 2021-01-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
