# Generated by Django 3.1.5 on 2021-02-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210203_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='delivery_time',
            new_name='delivery_duration',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
